## 문제 설명
어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.

- 제한사항
absolutes의 길이는 1 이상 1,000 이하입니다.
absolutes의 모든 수는 각각 1 이상 1,000 이하입니다.
signs의 길이는 absolutes의 길이와 같습니다.
signs[i] 가 참이면 absolutes[i] 의 실제 정수가 양수임을, 그렇지 않으면 음수임을 의미합니다.

- 입출력 예

|absolutes|signs|result|
|:---|:---|:---|
|[4,7,12]|[true,false,true]|9|
|[1,2,3]|[false,false,true]|0|




In [23]:
import numpy as np
ab = [4,7,12]
ab2 = [1,2,3]
signs1 = [True, False, True]
signs2 = [False, False, True]

In [41]:
import numpy as np
def solution(absolutes, signs):
    sign = []
    for sg in signs:
        if sg == False:
            sign.append(-1)
        else:
            sign.append(1)
    
    absolutes2 = np.array(absolutes)
    sign2 = np.array(sign)
    print(absolutes2)
    print(sign2)
    answer = absolutes2 * sign2
    print(answer)
    
    return int(sum(answer))


In [42]:
solution(ab2, signs2)

[1 2 3]
[-1 -1  1]
[-1 -2  3]


0

## - 인상깊었던 답

In [43]:
def solution(absolutes, signs):

    return sum(ab if sg else -ab for ab, sg in zip(absolutes, signs))

In [46]:
ab = [1,2,3]



print(sum(ab2 for ab2 in ab))

6
